package com.ml.epic.ta.model;

import java.util.Date;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Queries")
public class Query {

	String id;
	String name;
	String value;
	String createdBy;
	Date createdAt;

	/**
	 * Instantiates a new query.
	 */
	public Query() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * Instantiates a new query.
	 *
	 * @param id        the id
	 * @param name      the name
	 * @param value     the value
	 * @param createdBy the created by
	 * @param createdAt the created at
	 */
	public Query(String id, String name, String value, String createdBy, Date createdAt) {
		super();
		this.id = id;
		this.name = name;
		this.value = value;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@DynamoDBAttribute(attributeName = "query_name")
	public String getName() {
		return name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	@DynamoDBAttribute(attributeName = "query_value")
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@DynamoDBAttribute(attributeName = "created_by")
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created at.
	 *
	 * @return the created at
	 */
	@DynamoDBAttribute(attributeName = "created_at")
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * Sets the created at.
	 *
	 * @param createdAt the new created at
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
